// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActualQuantity():Promise<number>;

export function SaveTrackerConfig(arg1:string):void;
