// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveTrackerConfig(arg1) {
  return window['go']['backend']['App']['SaveTrackerConfig'](arg1);
}
