// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';

export function GetActualQuantity():Promise<json.Number>;

export function SaveTrackerConfig(arg1:string):void;

export function SetActualQuantity(arg1:string):void;
