// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActualPercent() {
  return window['go']['backend']['App']['GetActualPercent']();
}

export function GetAppHistoryWithPage(arg1) {
  return window['go']['backend']['App']['GetAppHistoryWithPage'](arg1);
}

export function GetTracker() {
  return window['go']['backend']['App']['GetTracker']();
}

export function SaveTrackerConfig(arg1) {
  return window['go']['backend']['App']['SaveTrackerConfig'](arg1);
}

export function SetActualQuantity(arg1) {
  return window['go']['backend']['App']['SetActualQuantity'](arg1);
}
