// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetActualPercent():Promise<number>;

export function GetTracker():Promise<backend.Tracker>;

export function SaveTrackerConfig(arg1:string):void;

export function SetActualQuantity(arg1:string):void;
